(cl:in-package beginner_tutorials-msg)
(cl:export '(NAME_ACCEL_GYRO-VAL
          NAME_ACCEL_GYRO
          DEVICEID_ACCEL_GYRO-VAL
          DEVICEID_ACCEL_GYRO
          ACCEL_X-VAL
          ACCEL_X
          ACCEL_Y-VAL
          ACCEL_Y
          ACCEL_Z-VAL
          ACCEL_Z
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          NAME_MAG-VAL
          NAME_MAG
          DEVICEID_MAG-VAL
          DEVICEID_MAG
          MAG_X-VAL
          MAG_X
          MAG_Y-VAL
          MAG_Y
          MAG_Z-VAL
          MAG_Z
          NAME_ALT_TEMP-VAL
          NAME_ALT_TEMP
          DEVICEID_ALT_TEMP-VAL
          DEVICEID_ALT_TEMP
          ALT-VAL
          ALT
          TEMP-VAL
          TEMP
))