// Generated by gencpp from file beginner_tutorials/Accel.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ACCEL_H
#define BEGINNER_TUTORIALS_MESSAGE_ACCEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Accel_
{
  typedef Accel_<ContainerAllocator> Type;

  Accel_()
    : name()
    , deviceID(0)
    , accel_x(0.0)
    , accel_y(0.0)
    , accel_z(0.0)  {
    }
  Accel_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , deviceID(0)
    , accel_x(0.0)
    , accel_y(0.0)
    , accel_z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _deviceID_type;
  _deviceID_type deviceID;

   typedef float _accel_x_type;
  _accel_x_type accel_x;

   typedef float _accel_y_type;
  _accel_y_type accel_y;

   typedef float _accel_z_type;
  _accel_z_type accel_z;





  typedef boost::shared_ptr< ::beginner_tutorials::Accel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Accel_<ContainerAllocator> const> ConstPtr;

}; // struct Accel_

typedef ::beginner_tutorials::Accel_<std::allocator<void> > Accel;

typedef boost::shared_ptr< ::beginner_tutorials::Accel > AccelPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Accel const> AccelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Accel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Accel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Accel_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Accel_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.deviceID == rhs.deviceID &&
    lhs.accel_x == rhs.accel_x &&
    lhs.accel_y == rhs.accel_y &&
    lhs.accel_z == rhs.accel_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Accel_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Accel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Accel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Accel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Accel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Accel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Accel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Accel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Accel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b08ed2f1c5084f033c7c9b5231e4229";
  }

  static const char* value(const ::beginner_tutorials::Accel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b08ed2f1c5084f0ULL;
  static const uint64_t static_value2 = 0x33c7c9b5231e4229ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Accel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Accel";
  }

  static const char* value(const ::beginner_tutorials::Accel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Accel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 deviceID\n"
"float32 accel_x\n"
"float32 accel_y\n"
"float32 accel_z\n"
;
  }

  static const char* value(const ::beginner_tutorials::Accel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Accel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.deviceID);
      stream.next(m.accel_x);
      stream.next(m.accel_y);
      stream.next(m.accel_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Accel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Accel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Accel_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "deviceID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.deviceID);
    s << indent << "accel_x: ";
    Printer<float>::stream(s, indent + "  ", v.accel_x);
    s << indent << "accel_y: ";
    Printer<float>::stream(s, indent + "  ", v.accel_y);
    s << indent << "accel_z: ";
    Printer<float>::stream(s, indent + "  ", v.accel_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ACCEL_H
