// Generated by gencpp from file beginner_tutorials/Temp.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TEMP_H
#define BEGINNER_TUTORIALS_MESSAGE_TEMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Temp_
{
  typedef Temp_<ContainerAllocator> Type;

  Temp_()
    : name()
    , deviceID(0)
    , temp(0.0)  {
    }
  Temp_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , deviceID(0)
    , temp(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _deviceID_type;
  _deviceID_type deviceID;

   typedef float _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::beginner_tutorials::Temp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Temp_<ContainerAllocator> const> ConstPtr;

}; // struct Temp_

typedef ::beginner_tutorials::Temp_<std::allocator<void> > Temp;

typedef boost::shared_ptr< ::beginner_tutorials::Temp > TempPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Temp const> TempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Temp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Temp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Temp_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Temp_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.deviceID == rhs.deviceID &&
    lhs.temp == rhs.temp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Temp_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Temp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Temp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Temp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Temp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Temp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Temp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0755a2ea399434f518ddd31b9aa172ec";
  }

  static const char* value(const ::beginner_tutorials::Temp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0755a2ea399434f5ULL;
  static const uint64_t static_value2 = 0x18ddd31b9aa172ecULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Temp";
  }

  static const char* value(const ::beginner_tutorials::Temp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 deviceID\n"
"float32 temp\n"
;
  }

  static const char* value(const ::beginner_tutorials::Temp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Temp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.deviceID);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Temp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Temp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Temp_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "deviceID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.deviceID);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TEMP_H
